# This is a configuration file for the Github Pages edition of a book by Chastity.
# This site is managed by Chastity White Rose, the Vegan Virgin.

title: Walking the Rainbow Bridge
description: Creating Conversations for Diversity, Equity, and Inclusion
