# This is a configuration file for the Github Pages edition of ChasteBase.
# This site is managed by Chastity White Rose, the Vegan Virgin

theme: minima

title: Walking the Rainbow Bridge
description: Creating Conversations for Diversity, Equity, and Inclusion
